/**
 * RTK Query API Configuration
 *
 * RTK Query is a data fetching and caching tool built on Redux Toolkit.
 * It simplifies API calls and automatically manages loading states, caching, and refetching.
 *
 * This file sets up the base API configuration that all API endpoints will use.
 */

import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import type {
  Email,
  EmailFilters,
  WhatsAppMessage,
  SendWhatsAppMessageRequest,
  UserWithPreferences, // Imported for the /me response
  UserPreferences,     // Imported for the mutation argument
  ApiResponse,
} from '@email-whatsapp-bridge/shared';

/**
 * Base API URL - will be different in production
 * In development, this points to the local Fastify server
 */
const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000/api';

/**
 * Base API configuration using RTK Query
 *
 * This creates a Redux slice that handles all API communication.
 * It automatically generates hooks like useGetEmailsQuery, useSendWhatsAppMessageMutation, etc.
 */
export const api = createApi({
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({
    baseUrl: API_BASE_URL,
    prepareHeaders: (headers) => {
      // Add authentication token if available
      const token = localStorage.getItem('auth_token');
      if (token) {
        headers.set('authorization', `Bearer ${token}`);
      }
      return headers;
    },
  }),
  tagTypes: ['Email', 'WhatsAppMessage', 'User'],
  endpoints: (builder) => ({
    /**
     * Get list of emails with optional filters
     */
    getEmails: builder.query<ApiResponse<Email[]>, EmailFilters | void>({
      query: (filters) => ({
        url: '/emails',
        // If filters is void/undefined, explicitly pass undefined
        params: filters || undefined,
      }),
      providesTags: ['Email'],
    }),

    /**
     * Get a single email by ID
     */
    getEmailById: builder.query<ApiResponse<Email>, string>({
      query: (id) => `/emails/${id}`,
      providesTags: ['Email'],
    }),

    /**
     * Send a WhatsApp message
     */
    sendWhatsAppMessage: builder.mutation<
      ApiResponse<WhatsAppMessage>,
      SendWhatsAppMessageRequest
    >({
      query: (body) => ({
        url: '/whatsapp/send',
        method: 'POST',
        body,
      }),
      invalidatesTags: ['WhatsAppMessage'],
    }),

    /**
     * Get WhatsApp message history
     */
    getWhatsAppMessages: builder.query<ApiResponse<WhatsAppMessage[]>, void>({
      query: () => '/whatsapp/messages',
      providesTags: ['WhatsAppMessage'],
    }),

    /**
     * Get current user information
     * Returns UserWithPreferences because the backend includes the relation
     */
    getCurrentUser: builder.query<ApiResponse<UserWithPreferences>, void>({
      query: () => '/user/me',
      providesTags: ['User'],
    }),

    /**
     * Update user preferences
     * Takes Partial<UserPreferences> and returns the updated Preferences object
     */
    updateUserPreferences: builder.mutation<
      ApiResponse<UserPreferences>,
      Partial<UserPreferences>
    >({
      query: (preferences) => ({
        url: '/user/preferences',
        method: 'PATCH',
        body: preferences,
      }),
      // Invalidating 'User' triggers a re-fetch of getCurrentUser, 
      // ensuring the UI reflects the new state globally.
      invalidatesTags: ['User'],
    }),

    /**
     * Sync emails from Gmail
     * This triggers the backend to fetch new emails from Gmail API
     */
    syncEmails: builder.mutation<ApiResponse<{ count: number }>, void>({
      query: () => ({
        url: '/emails/sync',
        method: 'POST',
      }),
      invalidatesTags: ['Email'],
    }),
  }),
});

/**
 * Export hooks for usage in functional components
 *
 * These hooks are automatically generated by RTK Query based on the endpoints above.
 * They handle loading states, errors, and caching automatically.
 *
 * Usage example:
 * const { data, isLoading, error } = useGetEmailsQuery({ isUnread: true });
 */
export const {
  useGetEmailsQuery,
  useGetEmailByIdQuery,
  useSendWhatsAppMessageMutation,
  useGetWhatsAppMessagesQuery,
  useGetCurrentUserQuery,
  useUpdateUserPreferencesMutation,
  useSyncEmailsMutation,
} = api;